import { HTTPFacilitatorClient } from "@x402/core/server";
import { x402ResourceServer, paymentMiddleware } from "@x402/express";
import { ExactEvmScheme } from "@x402/evm/exact/server";
import type { Network } from "@x402/express";
import type { RequestHandler } from "express";
import { config } from "./config.js";

export function createX402Middleware(): RequestHandler {
  const network = config.X402_NETWORK as Network;
  const facilitatorClient = new HTTPFacilitatorClient({
    url: config.X402_FACILITATOR_URL
  });

  const resourceServer = new x402ResourceServer(facilitatorClient).register(network, new ExactEvmScheme());

  return paymentMiddleware(
    {
      "POST /api/v1/reports": {
        accepts: {
          scheme: "exact",
          price: config.X402_PRICE_USD,
          network,
          payTo: config.AGENT_PAYOUT_ADDRESS,
          maxTimeoutSeconds: 120
        },
        description: "Paid on-chain research report generated by Cryptoclaw"
      }
    },
    resourceServer
  );
}
