import { HTTPFacilitatorClient, type RoutesConfig } from "@x402/core/server";
import {
  x402ResourceServer,
  x402HTTPResourceServer,
  paymentMiddlewareFromHTTPServer
} from "@x402/express";
import { ExactEvmScheme } from "@x402/evm/exact/server";
import type { Network } from "@x402/express";
import type { RequestHandler } from "express";
import { config } from "./config.js";
import { logger } from "./logger.js";

/**
 * PaymentHandler encapsulates x402 payment middleware for Express.
 *
 * Lifecycle:
 *  1. An unprotected request arrives at a guarded route.
 *     onProtectedRequest logs whether the request carries a payment header.
 *     If the header is absent the middleware issues a 402 with full payment
 *     requirements so the client knows exactly what to pay and where.
 *  2. The client attaches the X-PAYMENT header and retries (the "callback").
 *     onAfterVerify fires when the facilitator confirms the payment is valid.
 *     onVerifyFailure fires when validation is rejected (wrong amount, expired,
 *     bad signature, etc.).
 *  3. After the route handler returns a 200 the payment is settled on-chain.
 *     onAfterSettle logs the transaction hash and payer address.
 *     onSettleFailure logs settlement errors without interrupting the response.
 */
export class PaymentHandler {
  private readonly httpServer: x402HTTPResourceServer;
  private readonly routesConfig: RoutesConfig;

  constructor() {
    const network = config.X402_NETWORK as Network;

    this.routesConfig = {
      "POST /api/v1/reports": {
        accepts: {
          scheme: "exact",
          price: config.X402_PRICE_USD,
          network,
          payTo: config.AGENT_PAYOUT_ADDRESS,
          maxTimeoutSeconds: 120
        },
        description: "Paid on-chain research report generated by Cryptoclaw"
      }
    };

    const facilitatorClient = new HTTPFacilitatorClient({
      url: config.X402_FACILITATOR_URL
    });

    const resourceServer = new x402ResourceServer(facilitatorClient)
      .register(network, new ExactEvmScheme())
      .onAfterVerify(async (ctx) => {
        logger.info(
          {
            payer: ctx.result.payer,
            network: ctx.requirements.network,
            asset: ctx.requirements.asset
          },
          "x402 payment verified"
        );
      })
      .onVerifyFailure(async (ctx) => {
        logger.warn(
          {
            err: ctx.error,
            network: ctx.requirements.network
          },
          "x402 payment verification failed"
        );
      })
      .onAfterSettle(async (ctx) => {
        logger.info(
          {
            txHash: ctx.result.transaction,
            payer: ctx.result.payer,
            network: ctx.result.network,
            amount: ctx.result.amount
          },
          "x402 payment settled"
        );
      })
      .onSettleFailure(async (ctx) => {
        logger.error(
          {
            err: ctx.error,
            network: ctx.requirements.network
          },
          "x402 payment settlement failed"
        );
      });

    this.httpServer = new x402HTTPResourceServer(resourceServer, this.routesConfig).onProtectedRequest(
      async (ctx) => {
        const hasPayment = Boolean(ctx.paymentHeader);
        logger.info(
          { method: ctx.method, path: ctx.path, hasPayment },
          hasPayment ? "x402 payment callback received" : "x402 payment required — returning 402"
        );
      }
    );
  }

  /** Returns the Express middleware that enforces x402 payment requirements. */
  middleware(): RequestHandler {
    return paymentMiddlewareFromHTTPServer(this.httpServer);
  }

  /** Exposes the route configuration for discovery / introspection endpoints. */
  get routes(): RoutesConfig {
    return this.routesConfig;
  }
}
